version: "3.9"

services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "${SWAGGERUIPORT}:${CONTAINER_SWAGGERUIPORT}"
    volumes:
      - ./api/openapi.yaml:/openapi.yaml
    environment:
      SWAGGER_JSON: /openapi.yaml
  backend:
    container_name: "backend-container"
    build: ./backend
    ports:
      - "${BACKENDPORT}:${CONTAINER_BACKENDPORT}"
    volumes:
      - ./backend:/backend
