version: "3.9"

services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "${SWAGGERUIPORT}:${CONTAINER_SWAGGERUIPORT}"
    volumes:
      - ./api/openapi.yaml:/openapi.yaml
    environment:
      SWAGGER_JSON: /openapi.yaml
  frontend:
    container_name: "frontend-container"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${FRONTENDPORT}:${CONTAINER_FRONTENDPORT}"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:${CONTAINER_BACKENDPORT}
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
      - /frontend/.next
  backend:
    container_name: "backend-container"
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${BACKENDPORT}:${CONTAINER_BACKENDPORT}"
    volumes:
      - ./backend:/backend
  db:
    image: postgres:17
    container_name: postgres-db
    ports:
      - "${DBPORT}:${CONTAINER_DBPORT}"
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
volumes:
  db-store:
  